apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "auction-frontend.name" . }}
  namespace: {{ .Values.metadata.namespace }}
  labels: 
    {{- include "auction-frontend.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts: 
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secret }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.rules.host | quote }}
      http:
        paths:
        - pathType: Prefix
          path: {{ .Values.ingress.rules.path }}
          backend:
            service:
              name: {{ .Values.service.name }}
              port: 
                number: {{ .Values.service.port }}
