{{- if .Values.ingress.enabled }}
{{- $sName := .Values.service.name }}
{{- $sPort := .Values.service.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "auction-frontend.name" . }}
  namespace: {{ .Values.metadata.namespace }}
  labels: 
    {{- include "auction-frontend.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts: 
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secret }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.rules }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .http.paths }}
      - pathType: {{ .pathType }}
        path: {{ .path | quote }}
        backend:
          service:
            name: {{ $sName }}
            port: 
              number: {{ $sPort }}
      {{- end }}
  {{- end }}
{{- end }}
