apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels: 
    {{- include "auction-frontend.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "auction-frontend.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
