apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    app: frontend
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
