apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: app
  labels:
    name: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: auction.racun.ninja
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port: 
              number: 3000
