apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: check-backend
          image: busybox:1.31
          envFrom:
            - configMapRef:
                name: frontend-configmap
          command:
            ['sh', '-c', 'until nc -z $backend 8080; do echo waiting; sleep 2; done;']
      containers:
      - name: frontend
        image: abhpraksa.azurecr.io/frontend
        resources:
          limits:
            memory: "1024M"
            cpu: "0.1"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
              - name: Test
                value: Test
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 10
      imagePullSecrets:
        - name: azure
