apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJjbG91ZC5jYW5pc3Rlci5pbzo1MDAwIjogewoJCQkiYXV0aCI6ICJZV05wWW1WbFpUcERJVUl6YUc5NFhuWllZMEJDT0E9PSIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  name: canister
  namespace: app
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-pass
  namespace: database
type: Opaque
data:
  password: cG9zdGdyZXM=
